import {
  Award,
  BadgeCheck,
  BookOpen,
  BriefcaseBusiness,
  Building2,
  CalendarCheck,
  CalendarDays,
  CalendarRange,
  Camera,
  ChartColumn,
  ChartPie,
  ClipboardCheck,
  ClipboardList,
  Clock3,
  Database,
  Eye,
  FileChartColumn,
  FileCheck2,
  FileUser,
  Files,
  Film,
  FolderOpen,
  Goal,
  GraduationCap,
  HeartHandshake,
  History,
  IdCard,
  Images,
  Landmark,
  LayoutGrid,
  ListChecks,
  NotebookPen,
  Paperclip,
  Presentation,
  TableProperties,
  Target,
  User,
  UserRound,
  Users,
  UsersRound,
  Workflow,
} from "lucide-react";
import type { LucideIcon } from "lucide-react";

export const SECTION_ICONS: Record<string, LucideIcon> = {
  "1": IdCard,
  "2": User,
  "3": Building2,
  "4": BookOpen,
  "5": LayoutGrid,
  "6": ClipboardList,
  "7": CalendarCheck,
  "8": Paperclip,
};

export const SUBSECTION_ICONS: Record<string, LucideIcon> = {
  "1.1": BriefcaseBusiness,
  "1.2": UserRound,
  "1.3": Clock3,
  "1.4": BadgeCheck,
  "2.1": Camera,
  "2.2": GraduationCap,
  "2.3": ChartPie,
  "2.4": FileUser,
  "2.5": IdCard,
  "2.6": Award,
  "3.1": Landmark,
  "3.2": History,
  "3.3": Target,
  "3.4": Eye,
  "3.5": HeartHandshake,
  "4.1": Presentation,
  "4.2": Database,
  "4.3": UsersRound,
  "4.4": FileCheck2,
  "4.5": Goal,
  "4.6": CalendarRange,
  "4.7": NotebookPen,
  "4.8": TableProperties,
  "5.1": Images,
  "5.1.1": Award,
  "5.1.2": Users,
  "5.1.3": Workflow,
  "6.1": ClipboardCheck,
  "6.2": ClipboardCheck,
  "6.3": ClipboardCheck,
  "6.4": ClipboardCheck,
  "6.5": ChartColumn,
  "7.1": ListChecks,
  "7.2": CalendarDays,
  "8.1": Files,
  "8.2": FileChartColumn,
  "8.3": Film,
};

export function PortfolioIcon({ code, size = 21 }: { code: string; size?: number }) {
  const Icon = SUBSECTION_ICONS[code] ?? SECTION_ICONS[code] ?? FolderOpen;
  return <Icon aria-hidden="true" size={size} strokeWidth={1.8} />;
}
